In [4]:
import polars as pl

In [4]:

categorical_cols = [
  'group', 'field_location', 'company',
  'resource', 'vessel', 'bucket', 'un'
]

In [8]:
df = pl.read_parquet( 'dados-submarinos-all.parquet' )

# ============================================================
# ENCODE CATEGORICAL COLUMNS
# ============================================================

#df = df.with_columns( [
#    pl.col( col ).cast( pl.Categorical ) for col in categorical_cols
#] )


#print( df.dtypes )

#import polars.selectors as cs

#df.describe(  )


df.select(cs.numeric()).describe( )

NameError: name 'cs' is not defined

In [36]:
 df.filter(
    pl.col("company").is_null()
).select('id',"vessel", "company")

shape: (2_521, 3)
┌────────┬──────────────────┬─────────┐
│ id     ┆ vessel           ┆ company │
│ ---    ┆ ---              ┆ ---     │
│ i32    ┆ cat              ┆ cat     │
╞════════╪══════════════════╪═════════╡
│ 112405 ┆ Skandi Olympia   ┆ null    │
│ 112404 ┆ R Apollo Z       ┆ null    │
│ 112403 ┆ R Apollo Z       ┆ null    │
│ 112402 ┆ Skandi Commander ┆ null    │
│ 112366 ┆ Skandi Olympia   ┆ null    │
│ …      ┆ …                ┆ …       │
│ 23428  ┆ Skandi Commander ┆ null    │
│ 21576  ┆ Skandi Commander ┆ null    │
│ 21175  ┆ Skandi Commander ┆ null    │
│ 16992  ┆ Skandi Commander ┆ null    │
│ 9700   ┆ Skandi Commander ┆ null    │
└────────┴──────────────────┴─────────┘

In [37]:
df.with_columns(
    pl.col("company").fill_null(
        pl.col("company")
            .forward_fill()
            .backward_fill()
            .over("vessel")
    )
)

shape: (47_775, 38)
┌────────┬────────────┬────────────┬───────┬───┬────────────┬────────────┬────────────┬────────────┐
│ id     ┆ os         ┆ os_physica ┆ group ┆ … ┆ bucket_phy ┆ base       ┆ folder     ┆ path       │
│ ---    ┆ ---        ┆ l          ┆ ---   ┆   ┆ sical      ┆ ---        ┆ ---        ┆ ---        │
│ i32    ┆ cat        ┆ ---        ┆ cat   ┆   ┆ ---        ┆ str        ┆ str        ┆ str        │
│        ┆            ┆ u32        ┆       ┆   ┆ u32        ┆            ┆            ┆            │
╞════════╪════════════╪════════════╪═══════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 112432 ┆ 6000792398 ┆ 7463       ┆ ANC   ┆ … ┆ 4044       ┆ recursos-e ┆ OS00600079 ┆ sistemas-a │
│        ┆            ┆            ┆       ┆   ┆            ┆ mbarcacoes ┆ 2398       ┆ ncoragem/r │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆            ┆ ecursos-em │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆            ┆ …          │
│ 112431 ┆ 6000797937 ┆ 7464       ┆ null  ┆ … ┆ 4045       ┆ recursos-e ┆ OS00600079 ┆ servicos-a │
│        ┆            ┆            ┆       ┆   ┆            ┆ mbarcacoes ┆ 7937       ┆ rvore-de-n │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆            ┆ atal-molha │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆            ┆ …          │
│ 112430 ┆ 6000797560 ┆ 7465       ┆ null  ┆ … ┆ 4045       ┆ recursos-e ┆ OS00600079 ┆ servicos-a │
│        ┆            ┆            ┆       ┆   ┆            ┆ mbarcacoes ┆ 7560       ┆ rvore-de-n │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆            ┆ atal-molha │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆            ┆ …          │
│ 112429 ┆ 6000789371 ┆ 7466       ┆ MIS   ┆ … ┆ 4039       ┆ recursos-e ┆ OS00600078 ┆ manutencao │
│        ┆            ┆            ┆       ┆   ┆            ┆ mbarcacoes ┆ 9371-P-52- ┆ -inspecao- │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆ INSP-DUTO- ┆ submarina/ │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆ …          ┆ …          │
│ 112428 ┆ 6000749623 ┆ 7467       ┆ MER   ┆ … ┆ 4039       ┆ recursos-e ┆ OS00600074 ┆ manutencao │
│        ┆            ┆            ┆       ┆   ┆            ┆ mbarcacoes ┆ 9623-P-67- ┆ -inspecao- │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆ POS-PULL-I ┆ submarina/ │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆ …          ┆ …          │
│ …      ┆ …          ┆ …          ┆ …     ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ 4178   ┆ 6000487025 ┆ 29657      ┆ EQS   ┆ … ┆ 4039       ┆ recursos-e ┆ OS00600048 ┆ manutencao │
│        ┆            ┆            ┆       ┆   ┆            ┆ mbarcacoes ┆ 7025-JGCO2 ┆ -inspecao- │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆ 1-014      ┆ submarina/ │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆            ┆ …          │
│ 4177   ┆ 6000486667 ┆ 29658      ┆ EQS   ┆ … ┆ 4039       ┆ recursos-e ┆ OS00600048 ┆ manutencao │
│        ┆            ┆            ┆       ┆   ┆            ┆ mbarcacoes ┆ 6667-JGCRT ┆ -inspecao- │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆ 21-020     ┆ submarina/ │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆            ┆ …          │
│ 4107   ┆ 6000558142 ┆ 29659      ┆ EQS   ┆ … ┆ 4039       ┆ recursos-e ┆ OS00600055 ┆ manutencao │
│        ┆            ┆            ┆       ┆   ┆            ┆ mbarcacoes ┆ 8142-JGMRL ┆ -inspecao- │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆ 21-027     ┆ submarina/ │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆            ┆ …          │
│ 3292   ┆ 6000530044 ┆ 29326      ┆ SFA   ┆ … ┆ 4039       ┆ recursos-e ┆ OS00600053 ┆ manutencao │
│        ┆            ┆            ┆       ┆   ┆            ┆ mbarcacoes ┆ 0044-SACBU ┆ -inspecao- │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆ Z20-139    ┆ submarina/ │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆            ┆ …          │
│ 1904   ┆ 6000553476 ┆ 29660      ┆ MER   ┆ … ┆ 4039       ┆ frente-uni ┆ 2020-10-13 ┆ manutencao │
│        ┆            ┆            ┆       ┆   ┆            ┆ dade-estac ┆ -OS0060005 ┆ -inspecao- │
│        ┆            ┆            ┆       ┆   ┆            ┆ ionaria-pr ┆ 53476-PIDF ┆ submarina/ │
│        ┆            ┆            ┆       ┆   ┆            ┆ …          ┆ …          ┆ …          │
└────────┴────────────┴────────────┴───────┴───┴────────────┴────────────┴────────────┴────────────┘

In [38]:
df_filled = df.with_columns(
    pl.col("company").fill_null(
        pl.col("company")
            .forward_fill()
            .backward_fill()
            .over("vessel")
    )
)
df_filled_records = df_filled.filter(
    pl.col("company").is_not_null() & df["company"].is_null()
)
df_filled_records

shape: (654, 38)
┌────────┬────────────┬────────────┬───────┬───┬────────────┬────────────┬────────────┬────────────┐
│ id     ┆ os         ┆ os_physica ┆ group ┆ … ┆ bucket_phy ┆ base       ┆ folder     ┆ path       │
│ ---    ┆ ---        ┆ l          ┆ ---   ┆   ┆ sical      ┆ ---        ┆ ---        ┆ ---        │
│ i32    ┆ cat        ┆ ---        ┆ cat   ┆   ┆ ---        ┆ str        ┆ str        ┆ str        │
│        ┆            ┆ u32        ┆       ┆   ┆ u32        ┆            ┆            ┆            │
╞════════╪════════════╪════════════╪═══════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 112405 ┆ 6000795361 ┆ 7489       ┆ GDS   ┆ … ┆ 4043       ┆ recursos-e ┆ 004_SOLjub ┆ geodesia-o │
│        ┆            ┆            ┆       ┆   ┆            ┆ mbarcacoes ┆ 26-004_600 ┆ ceanografi │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆ 0795361    ┆ a/recursos │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆            ┆ …          │
│ 112366 ┆ 6000759249 ┆ 7525       ┆ GDS   ┆ … ┆ 4043       ┆ recursos-e ┆ 009_SOLjub ┆ geodesia-o │
│        ┆            ┆            ┆       ┆   ┆            ┆ mbarcacoes ┆ 26-009_600 ┆ ceanografi │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆ 0759249    ┆ a/recursos │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆            ┆ …          │
│ 112348 ┆ 6000759293 ┆ 7542       ┆ GDS   ┆ … ┆ 4043       ┆ recursos-e ┆ 008_SOLjub ┆ geodesia-o │
│        ┆            ┆            ┆       ┆   ┆            ┆ mbarcacoes ┆ 26-008_600 ┆ ceanografi │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆ 0759293    ┆ a/recursos │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆            ┆ …          │
│ 112347 ┆ 6000759289 ┆ 7543       ┆ GDS   ┆ … ┆ 4043       ┆ recursos-e ┆ 007_SOLjub ┆ geodesia-o │
│        ┆            ┆            ┆       ┆   ┆            ┆ mbarcacoes ┆ 26-007_600 ┆ ceanografi │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆ 0759289    ┆ a/recursos │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆            ┆ …          │
│ 112323 ┆ 6000781767 ┆ 7566       ┆ GDS   ┆ … ┆ 4043       ┆ recursos-e ┆ 006_SOLro2 ┆ geodesia-o │
│        ┆            ┆            ┆       ┆   ┆            ┆ mbarcacoes ┆ 6-006_6000 ┆ ceanografi │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆ 781767     ┆ a/recursos │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆            ┆ …          │
│ …      ┆ …          ┆ …          ┆ …     ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ 81820  ┆ 6000708876 ┆ 2761       ┆ GDS   ┆ … ┆ 4043       ┆ recursos-e ┆ 026 - SOLa ┆ geodesia-o │
│        ┆            ┆            ┆       ┆   ┆            ┆ mbarcacoes ┆ b24-026_60 ┆ ceanografi │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆ 00708876   ┆ a/recursos │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆            ┆ …          │
│ 81819  ┆ 6000687317 ┆ 2762       ┆ GDS   ┆ … ┆ 4043       ┆ recursos-e ┆ 025 - SOLm ┆ geodesia-o │
│        ┆            ┆            ┆       ┆   ┆            ┆ mbarcacoes ┆ rl24-025_6 ┆ ceanografi │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆ 000687317  ┆ a/recursos │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆            ┆ …          │
│ 81818  ┆ 6000693061 ┆ 2763       ┆ GDS   ┆ … ┆ 4043       ┆ recursos-e ┆ 024 - SOLm ┆ geodesia-o │
│        ┆            ┆            ┆       ┆   ┆            ┆ mbarcacoes ┆ rl23-024_6 ┆ ceanografi │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆ 000693061  ┆ a/recursos │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆            ┆ …          │
│ 81817  ┆ 6000692189 ┆ 2766       ┆ GDS   ┆ … ┆ 4043       ┆ recursos-e ┆ 021 - SOLm ┆ geodesia-o │
│        ┆            ┆            ┆       ┆   ┆            ┆ mbarcacoes ┆ ls24-021_6 ┆ ceanografi │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆ 000692189  ┆ a/recursos │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆            ┆ …          │
│ 81816  ┆ 6000709853 ┆ 2764       ┆ ANC   ┆ … ┆ 4043       ┆ recursos-e ┆ 023 - SOLm ┆ geodesia-o │
│        ┆            ┆            ┆       ┆   ┆            ┆ mbarcacoes ┆ rl24-023_6 ┆ ceanografi │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆ 000709853  ┆ a/recursos │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆            ┆ …          │
└────────┴────────────┴────────────┴───────┴───┴────────────┴────────────┴────────────┴────────────┘

In [41]:
df_filled = df.with_columns(
    pl.col("company").fill_null(
        pl.col("company")
            .forward_fill()
            .backward_fill()
            .over("vessel")
    )
)
df_filled_records = df_filled.filter(
    df["company"].is_null()
).select(
    "id",
    "vessel",
    "company"
)
df_filled_records.head( )

shape: (5, 3)
┌────────┬──────────────────┬─────────┐
│ id     ┆ vessel           ┆ company │
│ ---    ┆ ---              ┆ ---     │
│ i32    ┆ cat              ┆ cat     │
╞════════╪══════════════════╪═════════╡
│ 112405 ┆ Skandi Olympia   ┆ DOF     │
│ 112404 ┆ R Apollo Z       ┆ null    │
│ 112403 ┆ R Apollo Z       ┆ null    │
│ 112402 ┆ Skandi Commander ┆ null    │
│ 112366 ┆ Skandi Olympia   ┆ DOF     │
└────────┴──────────────────┴─────────┘

In [55]:
df_filled = df.with_columns(
    pl.col("resource").fill_null(
        pl.col("resource")
            .forward_fill()
            .backward_fill()
            .over("vessel")
    )
)

In [56]:
pl.DataFrame(
    {"before": df["resource"], "after": df_filled["resource"]}
).filter(
    pl.col("before").is_null() & pl.col("after").is_not_null()
).height

0

In [49]:
print(f"Records actually filled: {filled_count}")

Records actually filled: 654

In [57]:
df.filter(
    pl.col("os").is_duplicated()
)

shape: (19_543, 38)
┌────────┬────────────┬────────────┬───────┬───┬────────────┬────────────┬────────────┬────────────┐
│ id     ┆ os         ┆ os_physica ┆ group ┆ … ┆ bucket_phy ┆ base       ┆ folder     ┆ path       │
│ ---    ┆ ---        ┆ l          ┆ ---   ┆   ┆ sical      ┆ ---        ┆ ---        ┆ ---        │
│ i32    ┆ cat        ┆ ---        ┆ cat   ┆   ┆ ---        ┆ str        ┆ str        ┆ str        │
│        ┆            ┆ u32        ┆       ┆   ┆ u32        ┆            ┆            ┆            │
╞════════╪════════════╪════════════╪═══════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 112432 ┆ 6000792398 ┆ 7463       ┆ ANC   ┆ … ┆ 4044       ┆ recursos-e ┆ OS00600079 ┆ sistemas-a │
│        ┆            ┆            ┆       ┆   ┆            ┆ mbarcacoes ┆ 2398       ┆ ncoragem/r │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆            ┆ ecursos-em │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆            ┆ …          │
│ 112429 ┆ 6000789371 ┆ 7466       ┆ MIS   ┆ … ┆ 4039       ┆ recursos-e ┆ OS00600078 ┆ manutencao │
│        ┆            ┆            ┆       ┆   ┆            ┆ mbarcacoes ┆ 9371-P-52- ┆ -inspecao- │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆ INSP-DUTO- ┆ submarina/ │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆ …          ┆ …          │
│ 112426 ┆ 6000743153 ┆ 7469       ┆ CRD   ┆ … ┆ 4039       ┆ recursos-e ┆ OS00600074 ┆ manutencao │
│        ┆            ┆            ┆       ┆   ┆            ┆ mbarcacoes ┆ 3153-CIMRL ┆ -inspecao- │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆ 26-014     ┆ submarina/ │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆            ┆ …          │
│ 112423 ┆ 6000756132 ┆ 7472       ┆ MER   ┆ … ┆ 4039       ┆ recursos-e ┆ OS00600075 ┆ manutencao │
│        ┆            ┆            ┆       ┆   ┆            ┆ mbarcacoes ┆ 6132-P-43- ┆ -inspecao- │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆ MPE-S-19-U ┆ submarina/ │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆ …          ┆ …          │
│ 112420 ┆ 6000731362 ┆ 7475       ┆ MER   ┆ … ┆ 4039       ┆ recursos-e ┆ OS60007313 ┆ manutencao │
│        ┆            ┆            ┆       ┆   ┆            ┆ mbarcacoes ┆ 62-SUBXVII ┆ -inspecao- │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆ IVL26-005  ┆ submarina/ │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆            ┆ …          │
│ …      ┆ …          ┆ …          ┆ …     ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ 4973   ┆ 6000590795 ┆ 29619      ┆ EQS   ┆ … ┆ 4039       ┆ recursos-e ┆ OS00600059 ┆ manutencao │
│        ┆            ┆            ┆       ┆   ┆            ┆ mbarcacoes ┆ 0795-JGMRL ┆ -inspecao- │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆ 21-051     ┆ submarina/ │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆            ┆ …          │
│ 4959   ┆ 6000573600 ┆ 29628      ┆ EQS   ┆ … ┆ 4039       ┆ recursos-e ┆ OS00600057 ┆ manutencao │
│        ┆            ┆            ┆       ┆   ┆            ┆ mbarcacoes ┆ 3600-JGBR2 ┆ -inspecao- │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆ 1-050      ┆ submarina/ │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆            ┆ …          │
│ 4954   ┆ 6000573600 ┆ 29628      ┆ EQS   ┆ … ┆ 4039       ┆ recursos-e ┆ OS00600057 ┆ manutencao │
│        ┆            ┆            ┆       ┆   ┆            ┆ mbarcacoes ┆ 3600-JGBR2 ┆ -inspecao- │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆ 1-045      ┆ submarina/ │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆            ┆ …          │
│ 4768   ┆ 6000591158 ┆ 29618      ┆ EQS   ┆ … ┆ 4039       ┆ recursos-e ┆ OS00600059 ┆ manutencao │
│        ┆            ┆            ┆       ┆   ┆            ┆ mbarcacoes ┆ 1158-JGMLL ┆ -inspecao- │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆ 21-013     ┆ submarina/ │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆            ┆ …          │
│ 3292   ┆ 6000530044 ┆ 29326      ┆ SFA   ┆ … ┆ 4039       ┆ recursos-e ┆ OS00600053 ┆ manutencao │
│        ┆            ┆            ┆       ┆   ┆            ┆ mbarcacoes ┆ 0044-SACBU ┆ -inspecao- │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆ Z20-139    ┆ submarina/ │
│        ┆            ┆            ┆       ┆   ┆            ┆            ┆            ┆ …          │
└────────┴────────────┴────────────┴───────┴───┴────────────┴────────────┴────────────┴────────────┘

In [59]:
df.select(
    pl.col("os")
).filter(
    pl.col("os").is_duplicated()
).unique()

shape: (7_410, 1)
┌────────────┐
│ os         │
│ ---        │
│ cat        │
╞════════════╡
│ 6000773717 │
│ 6000709826 │
│ 6000695074 │
│ 6000603669 │
│ 6000672617 │
│ …          │
│ 6000686277 │
│ 6000726265 │
│ 6000787815 │
│ 6000767365 │
│ 6000769828 │
└────────────┘

In [9]:
df = df.with_columns(
    pl.col("os")
        .count()
        .over("os")
        .alias("os_count")
)

cols = df.columns
cols.remove("os_count")
insert_at = 
cols.insert( cols.index( 'os' ) + 1, 'os_count' )
df.select( cols )

shape: (47_775, 39)
┌────────┬────────────┬─────────────┬───────┬───┬─────────────┬────────────┬────────────┬──────────┐
│ id     ┆ os         ┆ os_physical ┆ group ┆ … ┆ base        ┆ folder     ┆ path       ┆ os_count │
│ ---    ┆ ---        ┆ ---         ┆ ---   ┆   ┆ ---         ┆ ---        ┆ ---        ┆ ---      │
│ i32    ┆ cat        ┆ u32         ┆ cat   ┆   ┆ str         ┆ str        ┆ str        ┆ u32      │
╞════════╪════════════╪═════════════╪═══════╪═══╪═════════════╪════════════╪════════════╪══════════╡
│ 112432 ┆ 6000792398 ┆ 7463        ┆ ANC   ┆ … ┆ recursos-em ┆ OS00600079 ┆ sistemas-a ┆ 2        │
│        ┆            ┆             ┆       ┆   ┆ barcacoes   ┆ 2398       ┆ ncoragem/r ┆          │
│        ┆            ┆             ┆       ┆   ┆             ┆            ┆ ecursos-em ┆          │
│        ┆            ┆             ┆       ┆   ┆             ┆            ┆ …          ┆          │
│ 112431 ┆ 6000797937 ┆ 7464        ┆ null  ┆ … ┆ recursos-em ┆ OS00600079 ┆ servicos-a ┆ 1        │
│        ┆            ┆             ┆       ┆   ┆ barcacoes   ┆ 7937       ┆ rvore-de-n ┆          │
│        ┆            ┆             ┆       ┆   ┆             ┆            ┆ atal-molha ┆          │
│        ┆            ┆             ┆       ┆   ┆             ┆            ┆ …          ┆          │
│ 112430 ┆ 6000797560 ┆ 7465        ┆ null  ┆ … ┆ recursos-em ┆ OS00600079 ┆ servicos-a ┆ 1        │
│        ┆            ┆             ┆       ┆   ┆ barcacoes   ┆ 7560       ┆ rvore-de-n ┆          │
│        ┆            ┆             ┆       ┆   ┆             ┆            ┆ atal-molha ┆          │
│        ┆            ┆             ┆       ┆   ┆             ┆            ┆ …          ┆          │
│ 112429 ┆ 6000789371 ┆ 7466        ┆ MIS   ┆ … ┆ recursos-em ┆ OS00600078 ┆ manutencao ┆ 4        │
│        ┆            ┆             ┆       ┆   ┆ barcacoes   ┆ 9371-P-52- ┆ -inspecao- ┆          │
│        ┆            ┆             ┆       ┆   ┆             ┆ INSP-DUTO- ┆ submarina/ ┆          │
│        ┆            ┆             ┆       ┆   ┆             ┆ …          ┆ …          ┆          │
│ 112428 ┆ 6000749623 ┆ 7467        ┆ MER   ┆ … ┆ recursos-em ┆ OS00600074 ┆ manutencao ┆ 1        │
│        ┆            ┆             ┆       ┆   ┆ barcacoes   ┆ 9623-P-67- ┆ -inspecao- ┆          │
│        ┆            ┆             ┆       ┆   ┆             ┆ POS-PULL-I ┆ submarina/ ┆          │
│        ┆            ┆             ┆       ┆   ┆             ┆ …          ┆ …          ┆          │
│ …      ┆ …          ┆ …           ┆ …     ┆ … ┆ …           ┆ …          ┆ …          ┆ …        │
│ 4178   ┆ 6000487025 ┆ 29657       ┆ EQS   ┆ … ┆ recursos-em ┆ OS00600048 ┆ manutencao ┆ 1        │
│        ┆            ┆             ┆       ┆   ┆ barcacoes   ┆ 7025-JGCO2 ┆ -inspecao- ┆          │
│        ┆            ┆             ┆       ┆   ┆             ┆ 1-014      ┆ submarina/ ┆          │
│        ┆            ┆             ┆       ┆   ┆             ┆            ┆ …          ┆          │
│ 4177   ┆ 6000486667 ┆ 29658       ┆ EQS   ┆ … ┆ recursos-em ┆ OS00600048 ┆ manutencao ┆ 1        │
│        ┆            ┆             ┆       ┆   ┆ barcacoes   ┆ 6667-JGCRT ┆ -inspecao- ┆          │
│        ┆            ┆             ┆       ┆   ┆             ┆ 21-020     ┆ submarina/ ┆          │
│        ┆            ┆             ┆       ┆   ┆             ┆            ┆ …          ┆          │
│ 4107   ┆ 6000558142 ┆ 29659       ┆ EQS   ┆ … ┆ recursos-em ┆ OS00600055 ┆ manutencao ┆ 1        │
│        ┆            ┆             ┆       ┆   ┆ barcacoes   ┆ 8142-JGMRL ┆ -inspecao- ┆          │
│        ┆            ┆             ┆       ┆   ┆             ┆ 21-027     ┆ submarina/ ┆          │
│        ┆            ┆             ┆       ┆   ┆             ┆            ┆ …          ┆          │
│ 3292   ┆ 6000530044 ┆ 29326       ┆ SFA   ┆ … ┆ recursos-em ┆ OS00600053 ┆ manutencao ┆ 8        │
│        ┆            ┆             ┆       ┆   ┆ barcacoes   ┆ 0044-SACBU ┆ -inspecao- ┆          │
│        ┆            ┆             ┆       ┆   ┆             ┆ Z20-139    ┆ submarina/ ┆          │
│        ┆            ┆             ┆       ┆   ┆             ┆            ┆ …          ┆          │
│ 1904   ┆ 6000553476 ┆ 29660       ┆ MER   ┆ … ┆ frente-unid ┆ 2020-10-13 ┆ manutencao ┆ 1        │
│        ┆            ┆             ┆       ┆   ┆ ade-estacio ┆ -OS0060005 ┆ -inspecao- ┆          │
│        ┆            ┆             ┆       ┆   ┆ naria-pr…   ┆ 53476-PIDF ┆ submarina/ ┆          │
│        ┆            ┆             ┆       ┆   ┆             ┆ …          ┆ …          ┆          │
└────────┴────────────┴─────────────┴───────┴───┴─────────────┴────────────┴────────────┴──────────┘